[package]
name = "register-app"
version = "0.1.0"

[[module]]
name = "register"
source = "wasmer/php:8.2"

[[command]]
name = "run"
module = "register"
runner = "wasi"
args = ["-S", "0.0.0.0:8080", "-t", "."]

[fs]
"." = "."

